name: Auto Deploy to dev bot in VPS after push to master

on:
  push:
    branches:
      - master
jobs:
  deploy:
    name: Deploy project
    permissions:
      deployments: write
    runs-on: ubuntu-latest
    steps:
      - name: Pull and test
        uses: appleboy/ssh-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_GITHUB_TOKEN }}
        with:
          host: ${{ secrets.VPS_IP }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          passphrase: ${{ secrets.SSH_PASSPHRASE }}
          port: ${{ secrets.PORT }}
          script: |
            cd naria-labs/rzulty-bot-dev/
            git checkout develop
            git pull origin develop
            git submodule update --remote --recursive
            npm ci
            npm test
      - name: Update modules and proc develop update pipeline
        uses: appleboy/ssh-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_GITHUB_TOKEN }}
        with:
          host: ${{ secrets.VPS_IP }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          passphrase: ${{ secrets.SSH_PASSPHRASE }}
          port: ${{ secrets.PORT }}
          script: |
            cd naria-labs/rzulty-bot-dev/
            git config user.name "Naria Labs"
            git add modules
            git commit -m "Automated module version update"
            git push